"""Add default admin user.

Revision ID: 3fbc52577c5c
Revises: 4c68a751c934
Create Date: 2025-01-23 00:25:27.440317

"""

from typing import Sequence, Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

from api.src.auth.manager import UserManager

# revision identifiers, used by Alembic.
revision: str = "3fbc52577c5c"
down_revision: Union[str, None] = "4c68a751c934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "avatar_id", existing_type=sa.VARCHAR(length=320), nullable=False)
    hashed_password = UserManager(None).password_helper.hash("admin")

    op.execute(
        f"INSERT INTO public.user (id, email, username, hashed_password, avatar_id, is_superuser, is_active, is_verified) VALUES ('{uuid4()}', 'admin@example.com', 'admin', '{hashed_password}', 'files/templates/profile.png', true, true, true);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "avatar_id", existing_type=sa.VARCHAR(length=320), nullable=True)
    op.execute("DELETE FROM public.user WHERE email = 'admin@example.com';")
    # ### end Alembic commands ###
